# Generated by Django 4.1.3 on 2022-12-02 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=256)),
                ('ticker', models.CharField(max_length=7)),
                ('currency', models.CharField(max_length=3)),
                ('exchange', models.CharField(max_length=3)),
                ('sri', models.BooleanField()),
                ('shares', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('invest', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.category')),
            ],
        ),
    ]
