# Generated by Django 4.1.3 on 2022-12-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shares',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
