# Generated by Django 4.1.3 on 2022-12-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_stock_currency_alter_stock_exchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='target',
            field=models.FloatField(default=0.3, max_length=4),
            preserve_default=False,
        ),
    ]
