# Generated by Django 4.1.3 on 2022-12-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
