# Generated by Django 4.1.3 on 2022-12-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_category_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='prev_price',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_change',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='value_change',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
    ]
