# Generated by Django 4.1.3 on 2022-12-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_stock_prev_price_stock_price_change_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='price_change',
            new_name='price_change_perc',
        ),
    ]
